services:
  - type: web
    name: sareso
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_USERNAME
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
