/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as JobsPostRouteImport } from './routes/jobs.post'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as CompanyNewRouteImport } from './routes/company.new'
import { Route as CompanyIdRouteImport } from './routes/company.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const JobsPostRoute = JobsPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => JobsRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const CompanyNewRoute = CompanyNewRouteImport.update({
  id: '/company/new',
  path: '/company/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIdRoute = CompanyIdRouteImport.update({
  id: '/company/$id',
  path: '/company/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/company/$id': typeof CompanyIdRoute
  '/company/new': typeof CompanyNewRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/post': typeof JobsPostRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/company/$id': typeof CompanyIdRoute
  '/company/new': typeof CompanyNewRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/post': typeof JobsPostRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/company/$id': typeof CompanyIdRoute
  '/company/new': typeof CompanyNewRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/post': typeof JobsPostRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/register'
    | '/search'
    | '/upload'
    | '/company/$id'
    | '/company/new'
    | '/jobs/$id'
    | '/jobs/post'
    | '/messages/$conversationId'
    | '/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/register'
    | '/search'
    | '/upload'
    | '/company/$id'
    | '/company/new'
    | '/jobs/$id'
    | '/jobs/post'
    | '/messages/$conversationId'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/register'
    | '/search'
    | '/upload'
    | '/company/$id'
    | '/company/new'
    | '/jobs/$id'
    | '/jobs/post'
    | '/messages/$conversationId'
    | '/profile/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  UploadRoute: typeof UploadRoute
  CompanyIdRoute: typeof CompanyIdRoute
  CompanyNewRoute: typeof CompanyNewRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/jobs/post': {
      id: '/jobs/post'
      path: '/post'
      fullPath: '/jobs/post'
      preLoaderRoute: typeof JobsPostRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/company/new': {
      id: '/company/new'
      path: '/company/new'
      fullPath: '/company/new'
      preLoaderRoute: typeof CompanyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$id': {
      id: '/company/$id'
      path: '/company/$id'
      fullPath: '/company/$id'
      preLoaderRoute: typeof CompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsPostRoute: typeof JobsPostRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsPostRoute: JobsPostRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  UploadRoute: UploadRoute,
  CompanyIdRoute: CompanyIdRoute,
  CompanyNewRoute: CompanyNewRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
